/**
 * Pre-renders pdf.testoza.com after `vite build` (client) and
 * `vite build --ssr` (server renderer):
 *  - one HTML file per page with its full content, title, canonical, social
 *    tags and JSON-LD already in place (crawlers and AI bots need no JS)
 *  - modulepreload/CSS hints for the page's own code chunk
 *  - sitemap.xml, _redirects, llms.txt and _routes.json
 * Cloudflare Pages then serves "edit-pdf.html" at "/edit-pdf" and 404.html
 * with a real 404 status.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'dist-pdf');
const serverDir = path.join(root, 'dist-pdf-server');

const server = await import(pathToFileURL(path.join(serverDir, 'entry-server.js')).href);
const { render, PAGES, REDIRECTS, SITEMAP_PAGES, UPDATED, headHtml, absoluteUrl } = server;

const templatePath = path.join(dist, 'pdf.html');
const template = fs.readFileSync(templatePath, 'utf8');
const manifestPath = path.join(dist, '.vite', 'manifest.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

// --- Code-splitting hints -------------------------------------------------
const PAGE_SOURCE = {
    home: 'src/pdf/pages/PdfToolsLanding.tsx',
    editor: 'src/pdf/pages/PdfEditorPage.tsx',
    hindi: 'src/pdf/pages/PdfEditorPage.tsx',
    latex: 'src/pdf/pages/LatexToPdfPage.tsx',
    chatgpt: 'src/pdf/pages/LatexToPdfPage.tsx',
    notFound: 'src/pdf/pages/NotFoundPage.tsx',
};
const entry = manifest['pdf.html'];
const alreadyLoaded = new Set();
(function walk(key) {
    const chunk = manifest[key];
    if (!chunk || alreadyLoaded.has(chunk.file)) return;
    alreadyLoaded.add(chunk.file);
    (chunk.imports || []).forEach(walk);
})('pdf.html');

/**
 * Stylesheets of the page's own code chunk, so it looks right before the app
 * starts. JavaScript is deliberately NOT modulepreloaded: fetching and compiling
 * it early competed with the first paint (Lighthouse mobile: 87 → 99 without).
 */
function hintsFor(key) {
    const seen = new Set();
    const css = new Set();
    const walk = (k) => {
        const chunk = manifest[k];
        if (!chunk || alreadyLoaded.has(chunk.file) || seen.has(chunk.file)) return;
        seen.add(chunk.file);
        (chunk.css || []).forEach((c) => css.add(c));
        (chunk.imports || []).forEach(walk);
    };
    walk('src/pdf/site/boot.tsx');
    walk(PAGE_SOURCE[key]);
    return [...css].map((f) => `<link rel="stylesheet" href="/${f}" />`).join('\n    ');
}

// --- Pages ----------------------------------------------------------------
for (const page of PAGES) {
    const url = page.key === 'notFound' ? '/404' : page.path;
    const app = render(url);
    const head = `${headHtml(page)}\n    ${hintsFor(page.key)}`;
    // Function replacers: a string replacement would turn "$$" in the page (LaTeX!) into "$".
    const html = template.replace('<!--head-->', () => head).replace('<!--app-->', () => app);
    if (html.includes('<!--head-->') || html.includes('<!--app-->')) throw new Error('Template placeholders were not replaced');
    fs.writeFileSync(path.join(dist, page.file), html);
    console.log(`  ${page.file.padEnd(22)} ${(Buffer.byteLength(html) / 1024).toFixed(1)} KB  ${page.title}`);
}
fs.unlinkSync(templatePath);
if (!entry) throw new Error('manifest has no pdf.html entry');

// --- sitemap.xml ----------------------------------------------------------
const urls = SITEMAP_PAGES.map((p) => {
    const image = p.app ? `\n    <image:image><image:loc>${absoluteUrl(p.app.screenshot)}</image:loc></image:image>` : '';
    return `  <url>\n    <loc>${absoluteUrl(p.path)}</loc>\n    <lastmod>${UPDATED}</lastmod>${image}\n  </url>`;
});
fs.writeFileSync(
    path.join(dist, 'sitemap.xml'),
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n${urls.join('\n')}\n</urlset>\n`,
);

// --- _redirects (301s for short and old URLs) -------------------------------
const redirects = REDIRECTS.flatMap(([from, to]) => [`${from} ${to} 301`, `${from}/ ${to} 301`]);
fs.writeFileSync(path.join(dist, '_redirects'), `# Generated by scripts/prerender-pdf.mjs from src/pdf/site/routes.ts\n${redirects.join('\n')}\n`);

// --- llms.txt ---------------------------------------------------------------
const llms = [
    '# Panna — free PDF tools by TestoZa',
    '',
    '> Panna (pdf.testoza.com) is a set of free, in-browser PDF tools made by TestoZa. Files are processed on the user’s device and never uploaded. No sign-up, no watermark.',
    '',
    '## Tools',
    '',
    ...SITEMAP_PAGES.filter((p) => p.app).map((p) => `- [${p.app.name}](${absoluteUrl(p.path)}): ${p.description}`),
    '',
    '## Guides',
    '',
    '- [Stop painting white boxes on your PDFs](https://blog.testoza.com/stop-painting-white-boxes-on-your-pdfs): the complete guide to Panna — every tool, how same-font editing and true erasing work, Hindi support, and a comparison with other PDF editors',
    '- [Panna in the TestoZa user guide](https://testoza.com/user-guide/pdf-tools)',
    '',
    '## About',
    '',
    `- [All PDF tools](${absoluteUrl('/')})`,
    '- [TestoZa — online test maker for teachers](https://testoza.com/)',
    '- [Support](https://testoza.com/support)',
    '',
];
fs.writeFileSync(path.join(dist, 'llms.txt'), llms.join('\n'));

// --- _routes.json -----------------------------------------------------------
// The repo's functions/ folder belongs to testoza.com; never run it on this site.
fs.writeFileSync(path.join(dist, '_routes.json'), JSON.stringify({ version: 1, include: ['/__panna_no_functions'], exclude: [] }, null, 2));

// --- Clean up build-only files ------------------------------------------------
fs.rmSync(path.join(dist, '.vite'), { recursive: true, force: true });
fs.rmSync(serverDir, { recursive: true, force: true });
console.log(`Pre-rendered ${PAGES.length} pages, sitemap (${SITEMAP_PAGES.length} URLs), ${redirects.length} redirects.`);
