from pydantic import BaseModel, HttpUrl, Field
from typing import Optional, List, Dict, Any
from datetime import datetime

class PageViewEvent(BaseModel):
    event_type: str = Field(..., description="E.g., page_view")
    fingerprint: str = Field(..., min_length=64, max_length=64, description="SHA-256 fingerprint hash")
    session_token: str = Field(..., description="UUID token generated by frontend")
    page_path: str = Field(..., max_length=500)
    page_title: Optional[str] = None
    referrer: Optional[str] = Field(None, max_length=2000)
    utm_source: Optional[str] = None
    utm_medium: Optional[str] = None
    utm_campaign: Optional[str] = None
    screen_width: Optional[int] = None
    screen_height: Optional[int] = None
    user_agent: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)

class DailyStatsResponse(BaseModel):
    stat_date: str
    total_visitors: int
    new_visitors: int
    returning_visitors: int
    total_sessions: int
    total_page_views: int
    avg_session_duration: float
    bounce_rate: float
    top_pages: List[Dict[str, Any]]
    top_referrers: List[Dict[str, Any]]
    device_breakdown: Dict[str, int]
    country_breakdown: Dict[str, int]
